#include "but/generator.hpp"
#include <sstream>
#include <stdexcept>

namespace but {

void Generator::validate(const Config& conf) const {
  if (conf.m_size <= 0 || conf.r_size <= 0)
    throw std::runtime_error("widths must be positive");
}

std::string Generator::generate_verilog(const Config& conf) const {
  const int m   = conf.m_size;
  const int r   = conf.r_size;
  const int res = conf.res_size;

  std::ostringstream o;

  o << "module " << "But_multiplier" << "#(\n"
    << "    parameter m_size = " << m << ",\n"
    << "    parameter r_size = " << r << ",\n"
    << "    parameter res_size = " << res << "\n"
    << ")\n(\n"
    << "    input wire [m_size-1:0] M,\n"
    << "    input wire [r_size-1:0] R,\n"
    << "    output wire [res_size-1:0] RES\n"
    << ");\n\n"
    << "    // Generated by booth_gen\n"
    << "    wire [r_size:0] zero = '0;\n"
    << "    wire signed [m_size-1:0] M_s = "
    << "    wire signed [m_size-1:0] M_signed = M; \n"
    << "    wire signed [m_size-1:0] M_neg = -M_s;\n\n"
    << "    wire signed [res_size:0] A = {M_s, zero};\n"
    << "    wire signed [res_size:0] S = {M_neg, zero};\n"
    << "    wire signed [res_size:0] P = {{(m_size){1'b0}}, R, 1'b0};\n\n"
    << "    wire signed [res_size:0] Pi_res [0:r_size];\n"
    << "    assign Pi_res[0] = P;\n\n"
    << "    genvar i;\n"
    << "    generate\n"
    << "      for (i = 0; i < r_size; i = i + 1) begin\n"
    << "        wire signed [res_size:0] t;\n"
    << "        assign t = (Pi_res[i][1:0] == 2'b01) ? Pi_res[i] + A :\n"
    << "                   (Pi_res[i][1:0] == 2'b10) ? Pi_res[i] + S :\n"
    << "                    Pi_res[i];\n"
    << "        assign Pi_res[i+1] = t >>> 1;\n"
    << "      end\n"
    << "    endgenerate\n\n"
    << "    assign RES = Pi_res[r_size][res_size:1];\n"
    << "endmodule\n";

  return o.str();
}

}
